# Related work 

To begin this section, we acknowledge that literature in this field has employed varied, and a times contradictory, definitions of hot events. For the remaining of this report, a 'hot extreme event' will describe an anomalously high spike in near-surface temperature (with respect to the local climatology) occurring over the timescale of a day. A 'heatwave' will then describe an event of prolonged anomalously high near-surface temperature on the order of multiple days or weeks. In addition to reviewing literature on hot extremes, this section also discusses heatwave research as they, although being distinct, often evolve together. 

## Mechanisms of hot extreme development

To present a holistic review of existing literature, the temporal evolution of hot extremes and heatwaves is examined with regards to three heat-generating mechanisms: **advection** involves the horizontal transport of warmer air into a cooler air mass; **adiabatic heating** arises from descending air that compresses and thus heats; **diabatic heating** involves radiative effects including sensible heat fluxes from the Earth's surface. The absence of the reverse mechanisms (cold air advection, ascending air and diabatic cooling) may also contribute to the formation of hot extremes. This characterisation provides a uniform basis to discuss atmospheric phenomena linked to hot extreme evolution and suggests a methodology, later discussed, to quantify the contribution of these physical processes to specific events. 

In the mid-latitudes, the major weather regime associated with hot extremes is atmospheric blocking - a pattern characterized by persistent anticyclonic activity that prevents the influence of the prevailing flows (A. Lupo, 2020). They develop regions of large subsidence and clear skies that promote strong radiative heating in summer (L. Kautz, et al, 2022). Indeed, atmospheric blocks co-locates with hot extremes, particularly well over the Northern (Northern: S. Pfahl and H. Wernli, 2012; L. Brunner et al., 2018) and Southern (A. Pezza et al., 2011) mid-latitudes, although with significant spatial variability and large land-ocean contrasts. Over Europe, Stefano et al. (2012) suggests that increased sensible heat fluxes from higher soil moisture content and/or hydrological pre-conditioning are partly responsible for the observed land patterns, while the land-ocean contrast may be explained by a lower temperature variability due to water's larger heat capacity. 

In the polar latitudes, a diversity of atypical mechanisms may evolve due to the presence of snow and ice-sheets. Generally, an enhanced albedo effect implies lower diabatic heating and the temperature inversion created by a cold surface temperature limits adiabatic heating. Some studies have also suggested that intrusions of sub-polar air into the Arctic, such as by atmospheric rivers (AR) - corridors of rapidly ascending sub-tropical air that transport moisture and heat north/south-wards - may disturb the polar climate (Ma et al., 2017, Papritz et al., 2023). This may lead to increasing downward longwave radiation that accelerates sea-ice melting (Kapsch et al., 2013 Mortin et al., 2016) and advective warming at both lower and upper levels (Papritz et al., 2023). Indeed, a case-study on the March 2022 East Antarctica heat extreme shows that intense atmospheric blocking initiated by an AR led to the weakening of the ice-sheet temperature inversion, intensifying adiabatic heating from subsiding air (Wille et al., 2022). 

In the tropics, weather is instead predominantly influenced by circulation anomalies (such as the El-Nino Southern Oscillation) and local moist convective systems (although anti-cyclonic activity may still be a major synoptic driver). The limited literature on tropical hot extremes and heatwaves finds strong association of hot extreme events with dry land conditions, indicative of strong coupling between land-surface processes and the atmosphere: anti-cyclonic activity yielding clear skies may enhance radiative heating and reduce soil-moisture (Geirinhas et al., 2018; Costa et al., 2022), in turn decreasing the potential of latent cooling - the loss of heat due to evaporation - and increasing sensible heat fluxes. Theoretical work by Byrne (2021) suggests that the onset of moist convection increases relative humidity which limits the growth of positive temperature anomalies. 

Soil moisture and its complex dependence with near-surface temperature is not only important in the tropics, but also in the extra-tropics. Low soil-moisture content may be associated with increased sensible and decreased latent heating, which may reduce the potential for precipitation from deep convection and/or support a blocking high-pressure system, thus enhancing dry conditions (Berg et al., 2013; Wang et al., 2019). In the context of climate change, Vogel et al. (2017) quantified the contribution of soil moisture - temperature feedbacks to regional increase in TX1day magnitude at more than 70\% in Central Europe and Central North America, and around 50\% in Amazonia, Northern Australia and Southern Africa. These mechanisms may evolve differently on small or relatively large temporal and spatial scales (McColl et al., 2019), further illustrating their complexity. A systematic and global analysis of their contribution to yearly hot extremes still lacks. 

Hot extreme events over oceans have received little attention in the literature, likely due to their smaller impact on human health. Due to the absence of land-surface processes and a cool ocean, large scale systems with large advective warming and local diabatic cooling are expect to control hot extreme development.

INCLUDE MATTHIAS PAPER REFERENCE HERE, AND A REPRODUCTION OF THE FIGURE TO SUMMARIZE THE ABOVE WORK.

## Variability of hot extreme events

We have until now focused on understanding the diverse mechanisms that yield hot extreme events, globally. Several studies have however focused on relating the variability of these processes to the resulting hot extremes variability. Over the European mid-latitudes, changes in variability have been attributed to an increase in anticyclonic activity and advective heating (Lenderink et al., 2007; Horton et al., 2015; Holmes et al., 2016; Wang et al., 2023) and to the local effects of soil-moisture (Quesada et al., 2012; Whan et al., 2015; Donat et al., 2017; Vogel et al., 2017). More generally, L. Suarez-Gutierrez et al. (2020) suggests investigating variability changes with regards to dynamical and thermodynamical sources, and concludes that the former - encompassing effects of atmospheric blocking - are the main drivers of hot extreme variability. 

The literature has also considered the dependence on different temporal scales to investigate changes in the distribution of hot extremes. E. Fischer and C. Schar (2008) quantified the projected changes in hot extreme variability over Europe with respect to the processes associated with inter-annual variability, intra-seasonal variability and the seasonal variability of summer months, finding the largest contribution from the former. Di Luca et al. (2020) quantifies contributions of annual and diurnal first and second-moment features to daily hot extremes over land, showing a diversity of global patterns. However, these approaches lack a direct interpretation since the temporal features may be associated to different physical processes in different regions. 

## Methods in hot extreme literature

The weather extremes literature has used two main methodologies: sensitivity and trajectory analysis. To motivate the following work, we give a brief overview of these approaches.

**Sensitivity analysis** (SA) is the most widely adopted approach to study the effects of initial conditions and model parameters on outputs of a system. It involves running different experiments with simulation tools (including numerical and data-driven models) and assessing the changes in distribution of the response. Formally, sensitivity is defined as the partial derivative of the response with regards to a predictor of interest. It is then related to causality: if one assumes a linear structural model, sensitivity is a measure of the causal effect of a variable on the response. SA literature has considered both local and global measures of sensitivity. The former involves evaluating the sensitivity at a given predictor value and therefore cannot conclude general causal relationships without strong assumptions. The latter presents a difficult problem and different approaches have been proposed that include many typical statistical estimators (Razavi and Gupta, 2015).

**Trajectory analysis** follows the changes to volumes of air - called parcels - along their flow within a dynamical system. In the context of extreme weather, it often involves the identification of an event within a numerical model and recursive calculation of the flow backwards in time. The output is then a timeseries of physical and model quantities that describe the state history of the parcel which gave rise to the extreme event. 

y quantifying the transport characteristics that give rise to extreme events, studies have focus on providing 

## Temperature anomaly decomposition

To this end, we focus on investigating yearly maxima of 1-day temperature anomaly averages, denoted TX1day. Using anomalies, rather than magnitudes, leads to a more natural interpretation of the components' contribution to extreme warming, since some processes of interest, such as warming from horizontal advection, arise due to climatological differences *** (explain better). The variation in TX1day and its relation to underlying physical processes is captured by using the decomposition of TX1day anomalies into contributions from horizontal advection, adiabatic warming and diabatic warming (1), according to M. Rothlisberger and L. Papritz (2023). These quantities are now referred to as the advective (adv), adiabatic (adiab) and diabatic (diab) temperature anomalies. The decomposition is derived with a Lagrangian perspective, meaning that it diagnostically evaluates the evolution of a parcel of air along its trajectory in 3D space and time.

At location $\mathbf{x}$ and some time $t_X$, the temperature anomaly $T'$ may be decomposed as follows:

\begin{equation}
\label{eq:t_decomp}
 \begin{split}
   T'(\mathbf{x},t_X)  & = - \int_{t_g}^{t_X} \frac{\partial \bar{T}}{\partial t} \, \text{d}\tau - \int_{t_g}^{t_X} \mathbf{\nu} \mathbf{\nabla}_h \bar{T} \, \text{d}\tau + \int_{t_g}^{t_X} \left[ \frac{\kappa T}{p} - \frac{\partial \bar{T}}{\partial p}\right] \omega \, \text{d}\tau + \int_{t_g}^{t_X} \left( \frac{p}{p_0} \right)^\kappa \frac{\text{D}\theta}{\text{D}t} \, \text{d}\tau   \\
   & = \qquad \text{seas} \qquad \, + \, \quad \quad \text{adv} \qquad \, \, + \qquad \qquad \text{adiab} \qquad \quad \,  + \qquad \quad \text{diab} 
\end{split}
\end{equation}

where $\bar{T}$ the temperature climatology; $t_g < t_X$ genesis time, the time at which $T'$ was last zero; $\mathbf{\nu}$ the horizontal wind velocity; $\mathbf{\nabla}_h$ the horizontal temperature gradient; $p$ pressure; $\omega$ vertical velocity; $\theta$ potential temperature. 

To apply this decomposition for the study of hot extremes, LAGRANTO is employed to compute back-trajectories of air parcels found near the surface of a location of a hot extreme event. Given data described section 3, for each year at each location, a total of 24 back-trajectories are obtained corresponding to the 3 lower model-levels for 8 timesteps with 3 hour intervals. Each trajectory is computed until genesis $t=t_g$ of the temperature anomaly of the parcel, up to a maximum of 120 time-steps. The final dataset is created by evaluating the integrals for each of the 24 trajectories and taking an average of the final decomposed temperature anomaly.

Evaluating the integrals involves two errors arising from discrete approximations of the continuous time domain: error 1 denotes the deviation from zero of $T'(\cdot ,t_g)$; error 2 denotes the remainder of the components, seasonality and error 1 subtracted from $T'$. These errors are usually small relative to hot extreme $T'$ magnitudes and are thus dropped from further analysis. In addition, since TX1day events evolve on sub-seasonal timescales, the seasonality term (seas) is small and is also dropped. These decisions are supported by Appendix A. 

## Conclusion 

Although a good general understanding of hot extreme evolution exists and more detailed assessments have been made regionally and for specific high-impact events, there then exists a knowledge-gap in quantifying the contribution of known physical processes to hot extreme magnitude variability globally. This manuscripts attempts to close this gap by first proposing a systematic analysis of second-moment characteristics of hot extreme events and second applying state-of-the-art deep-learning methods to uncover evolutionary features influencing their magnitudes. 

## EXTRA STUFF

(probably too detailed, same references) 
In tropical Southern America, large anti-cyclonic systems (South Atlantic Subtropical High System) have been related to positive sea surface temperature anomalies of the South Atlantic and the weakening of the Intertropical Convergence Zone (ITCZ) and the South Atlantic Convergence Zone (SACZ) systems.

(maybe we can also mention these, but the major stuff was covered)
Numerous studies have linked changes in hot extreme intensity to large-scale patterns such as the El Nino Southern Oscillation and the Arctic Oscillation (Gao et al., 2017; ). Then A. Casanueva et al. (2014) propose investigating the variability of extreme precipitation events through large-scale teleconnection patterns, such as the Southern Oscillation and the North Atlantic Oscillation, by trend analysis and correlation analysis. 

designs for causal effect estimation (regression, factorial designs, 'regional SA' which seems to be just comparison of distributions at different quantiles, correlation or variance-based metrics, entropy-based metrics). 