# Conclusion

## Summary 

Hot extremes present a threat to human health, the economy and sensitive ecosystems. Although the variability in yearly hot extreme magnitudes has been studied and regionally linked to various physical mechanisms, a global view on these events lacks. This thesis bridges this gap by exploring the spatial variability observed in the year-to-year variability of TX1day events and link it to the year-to-year variability in the contribution from advective, adiabatic and diabatic heat-generating mechanisms. By considering the Lagrangian approach proposed by \cite{rothlisberger_quantifying_2023}, its mean-state characterizations are extended to a comprehensive second-moment analysis.

Global patterns in TX1day $T'$ variance are found to be similar to TX1day $T'$ magnitudes, with predominantly larger variance over land and increasing with increasing latitude. There is however more defined land-ocean contrasts, particularly on the Western coasts of continents between 25$^\circ$ and 60$^{\circ}$ North and 15$^\circ$ and 60$^\circ$ South with up to 16$^\circ$C$^2$ differences in variance in just 100km. No physical process is found to dominate TX1day event variability and the processes dominating the mean exhibit again similar patterns to those in the variance. Only few local regions - including the high-variability Western coasts - have a single contributor dominating the variance and these generally agree with the mean behavior. However, dominance in the mean by a contributor does not imply dominance in the variance only by this contributor, with more complete contributions from all three processes globally. Most significantly, this analysis finds that diabatic $T'$ variance contributions are often large, despite negative contribution in the mean. This suggests that diabatic processes through diverse land-atmosphere feedbacks and cloud-cover are important in year-to-year variability of hot extremes. This supports existing literature \citep{wehrli_identifying_2019,miralles_mega-heatwave_2014,schumacher_amplification_2019}, although finding a larger influence in the mid- to high-latitudes than \cite{wehrli_extremex_2022}.

Furthermore, the large and mostly negative covariances in \@ref(fig:vardecomp) are examined through PCA, finding that most of the globe has the variability of the three contributors constrained to only one or two axes of variability. This implies that, particularly over oceans, complex mechanisms suggested by the variance decomposition and supported in the literature can be more simply characterized. In regions with variance that remains poorly explained by two axes, contributors then act more independently which may suggest the influence of a larger diversity of physical mechanisms along parcel trajectories. These areas are found in high latitudes, such as over Northern Russia and Canada, and further suggests that Arctic amplification \citep{cohen_recent_2014} may be responsible for this complexity. 

**Conclusions drawn from Trajectory Analysis go here**

## Limitations and future work

Although providing novel insights into the global variability of physical processes contributing to hot extreme development, the methods proposed have several limitations. First of all, the variance decomposition cannot lead to any causal claims and inter-contributor dependencies must be interpreted collectively. PCA provided an efficient way to inspect these dependencies, but 

Future work may focus on extending the timeseries analysis. This thesis has shown that the complex and diverse timeseries behaviours, in addition to a large dataset, can be modeled successfully by a single LSTM-based architecture. The analysis stopped short of providing more insights into the role of each physical process in generating variability in the final $T'$. This relatively simple model combined with explainable artificial intelligence methods such as Shapely Additive exPlanations \citep[SHAP, ][]{lundberg_unified_2017} and related extensions to sequential data \citep[e.g. ][]{bento_timeshap_2021,nayebi_windowshap_2023} may be effective in uncovering the temporal features of each contributor important in making large final predictions. This would for example allow leveraging the temporal structure of the data to extract Granger-causal relationships between the contributors. 
